from flask_restful import Resource, reqparse
from src.UseCases.FindWebsitesByQuery import FindWebsitesByQuery
from src.UseCases.IndexWebsite import IndexWebsite

# Parser for POST requests
post_parser = reqparse.RequestParser(bundle_errors=True)

post_parser.add_argument('text', type=str, required=True)
post_parser.add_argument('url', type=str, required=True)
post_parser.add_argument('title', type=str, required=True)

# Parser for GET requests
get_parser = reqparse.RequestParser(bundle_errors=True)

get_parser.add_argument('query', type=str, required=True)


class Websites(Resource):
    '''Works as coordinator to use cases that affects to Website resources'''

    def __init__(self, save_visited_site: IndexWebsite, find_sites_by_query: FindWebsitesByQuery):
        self.__save_visited_site = save_visited_site
        self.__get_visited_sites = find_sites_by_query

    def options(self):
        return {'Allow': 'OPTIONS, GET, PUT'}, 200

    def put(self):
        # Instead of using arguments directly, Data Transfer Objects can be
        # used. The validation done in the current model, should be done in the
        # DTO creator service, and should be fail before enter into the domain.
        arguments = post_parser.parse_args()

        self.__save_visited_site.execute(arguments)
        # This message should be generated by the domain in a notification
        # service.
        return f'Text content from {arguments["title"]} stored successfully', 201

    def get(self):
        arguments = get_parser.parse_args()

        # To avoid breaking with the commander patter, a event comunication
        # system should be implemented, such as domain events. For now there is
        # no other need for it.
        visited_sites = self.__get_visited_sites.execute(arguments)

        print(f'{arguments} /n{visited_sites }')

        visited_site_dtos = []

        return visited_site_dtos, 200
